name: PHP tests on Postgres

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  run:
    name: PHP 7.2 Test
    runs-on: ubuntu-latest

    steps:
      - name: Allow runner as root
        run: export RUNNER_ALLOW_RUNASROOT=1

      - name: Update permission
        run: sudo chown -R $USER:$USER ${{ github.workspace }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run docker compose up
        run: docker-compose up -d

      - name: Services
        runa: docker ps

      - name: Curl test
        run: curl 127.0.0.1:8080
